NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/192.168.31.119-7054-ca-org1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/192.168.31.119-7054-ca-org1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/192.168.31.119-7054-ca-org1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/192.168.31.119-7054-ca-org1.pem
    OrganizationalUnitIdentifier: orderer
