NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/192.168.0.119-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/192.168.0.119-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/192.168.0.119-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/192.168.0.119-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer
